services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: myapp_development
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_development
      RAILS_LOG_TO_STDOUT: "true"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/rails:cached
      - bundle:/usr/local/bundle

  css:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./bin/rails tailwindcss:watch
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/myapp_development
    volumes:
      - .:/rails:cached
      - bundle:/usr/local/bundle
    depends_on:
      - db

volumes:
  db_volume:
  bundle:
